export const FETCH_USER_SALT='FETCH_USER_SALT';
export const USER_lOGIN='USER_lOGIN';
export const USER_lOGIN_FAILED='USER_lOGIN_FAILED';
export  const USER_OUT='USER_OUT'
export const COMMIT_DEVICEINFO = 'COMMIT_DEVICEINFO';
export const COMMIT_DEVICEINFO_FAILED = 'COMMIT_DEVICEINFO_FAILED';